### ISSUE TITLE
FillFormRequest.Ask timeout

### ISSUE THREAD

**Issue by Zaubererbruder** [immmdreza/FlamingoFramework#6]
Hello.

I want to fill Form by FillFormRequest, but it seems doesn't work as i expected. The timeout will expire several times, decreasing the error counter triesOnFailure. So bot sends several timeout messages before stops waiting answer. And also after completing Ask Task if filler not Completed and not Canceled, I can't understand it is because of timeout or failures

`await filler.Ask(
                Cdmt.SenderId,
                triesOnFailure: 3,
                timeOut: 60,
                cancellInputPattern: new Regex("^/cancel"));`

**Comment by immmdreza** [comment]
> Hello.
> 
> I want to fill Form by FillFormRequest, but it seems doesn't work as i expected. The timeout will expire several times, decreasing the error counter triesOnFailure. So bot sends several timeout messages before stops waiting answer. And also after completing Ask Task if filler not Completed and not Canceled, I can't understand it is because of timeout or failures
> 
> `await filler.Ask( Cdmt.SenderId, triesOnFailure: 3, timeOut: 60, cancellInputPattern: new Regex("^/cancel"));`

Thank you for reporting @Zaubererbruder, i will check as soon as i can

**Comment by immmdreza** [comment]
About the first issue: it's actually a normal behavior, because timeout considered as some kind of failure and after timeout, flamingo waits for an answer again ( depending on `triesOnFailure` ). in another word, that timeout parameter is not general and it's for each question separately. but yeah it looks annoying, I guess I can add a general timeout parameter or easily remove that message and even other kind of customization for that.
And about the second issue: yeah you're right. a `TimedOut` property is required.

I'll mark this as an enhancement and I will apply changes soon. Thanks you again for contributing.  
If you have any suggestions on this please note.
